"""add reference_urls to indicators

Revision ID: 258995358532
Revises: f1f21acb25cd
Create Date: 2026-05-02 04:17:19.469431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '258995358532'
down_revision: Union[str, None] = 'f1f21acb25cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indicators', sa.Column('reference_urls', postgresql.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indicators', 'reference_urls')
    # ### end Alembic commands ###
