"""create initial schema

Revision ID: f1f21acb25cd
Revises: 
Create Date: 2026-05-02 03:42:32.045999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1f21acb25cd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tld', sa.String(length=63), nullable=True),
    sa.Column('registrar', sa.String(length=255), nullable=True),
    sa.Column('registered_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domains_id'), 'domains', ['id'], unique=False)
    op.create_index(op.f('ix_domains_name'), 'domains', ['name'], unique=True)
    op.create_index(op.f('ix_domains_tld'), 'domains', ['tld'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('FEED', 'REPORT', 'MANUAL', 'MISP_EVENT', 'STIX_BUNDLE', name='source_type_enum'), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_id'), 'sources', ['id'], unique=False)
    op.create_index(op.f('ix_sources_name'), 'sources', ['name'], unique=True)
    op.create_table('indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicator_type', sa.Enum('IPV4', 'IPV6', 'URL', 'DOMAIN', 'MD5', 'SHA1', 'SHA256', 'EMAIL', 'ASN', 'BITCOIN_ADDRESS', 'MUTEX', 'FILE_PATH', 'REGISTRY_KEY', name='indicator_type_enum'), nullable=False),
    sa.Column('value', sa.String(length=2048), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CONFIRMED', name='confidence_enum'), nullable=False),
    sa.Column('tlp', sa.Enum('CLEAR', 'GREEN', 'AMBER', 'AMBER_STRICT', 'RED', name='tlp_enum'), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicators_domain_id'), 'indicators', ['domain_id'], unique=False)
    op.create_index(op.f('ix_indicators_id'), 'indicators', ['id'], unique=False)
    op.create_index(op.f('ix_indicators_indicator_type'), 'indicators', ['indicator_type'], unique=False)
    op.create_index(op.f('ix_indicators_source_id'), 'indicators', ['source_id'], unique=False)
    op.create_index(op.f('ix_indicators_value'), 'indicators', ['value'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('indicator_id', sa.Integer(), nullable=True),
    sa.Column('note_type', sa.Enum('ATTRIBUTION', 'VICTIMOLOGY', 'TTP', 'HYPOTHESIS', 'COMMENT', name='note_type_enum'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CONFIRMED', name='confidence_enum'), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('reference_urls', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_domain_id'), 'notes', ['domain_id'], unique=False)
    op.create_index(op.f('ix_notes_id'), 'notes', ['id'], unique=False)
    op.create_index(op.f('ix_notes_indicator_id'), 'notes', ['indicator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notes_indicator_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_domain_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_indicators_value'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_source_id'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_indicator_type'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_id'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_domain_id'), table_name='indicators')
    op.drop_table('indicators')
    op.drop_index(op.f('ix_sources_name'), table_name='sources')
    op.drop_index(op.f('ix_sources_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_domains_tld'), table_name='domains')
    op.drop_index(op.f('ix_domains_name'), table_name='domains')
    op.drop_index(op.f('ix_domains_id'), table_name='domains')
    op.drop_table('domains')
    # ### end Alembic commands ###
