"""add enrichments table

Revision ID: fa71515308f8
Revises: 258995358532
Create Date: 2026-05-04 03:28:47.937907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa71515308f8'
down_revision: Union[str, None] = '258995358532'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrichments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('enrichment_type', sa.Enum('DNS', 'EMAIL_SECURITY', 'WHOIS', 'CT_LOGS', 'TYPO_SQUAT', name='enrichment_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('OK', 'ERROR', 'TIMEOUT', 'RATE_LIMITED', 'NOT_FOUND', name='enrichment_status_enum'), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id', 'enrichment_type', name='uq_domain_enrichment_type')
    )
    op.create_index(op.f('ix_enrichments_domain_id'), 'enrichments', ['domain_id'], unique=False)
    op.create_index(op.f('ix_enrichments_enrichment_type'), 'enrichments', ['enrichment_type'], unique=False)
    op.create_index(op.f('ix_enrichments_id'), 'enrichments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enrichments_id'), table_name='enrichments')
    op.drop_index(op.f('ix_enrichments_enrichment_type'), table_name='enrichments')
    op.drop_index(op.f('ix_enrichments_domain_id'), table_name='enrichments')
    op.drop_table('enrichments')
    # ### end Alembic commands ###
